#!/usr/bin/env python3
"""review — health report of a finished (or running) analysis: coverage, vocabulary use, staleness, concentration, single-source risk.

  review.py [--out indexes/review.md] [--clone1 PATH] [--clone2 PATH]

Everything is computed from the records (and, when present, the thread caches under .cache/ and git clones). It prints/writes a markdown
report with an ATTENTION list: the things a reader of the dataset should know before relying on it. Thresholds are heuristics.
Sections: coverage and depth; facet population; class coverage and redundancy with a facet; citation coverage by documents/registry;
time concentration; confidence mix; unresolved outcomes; corrections; constraints not cited; maintainer behaviour; duplicated summaries.
"""
import argparse, collections, datetime, json, os, re, statistics, subprocess, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pz  # noqa: E402

MIN_N = 30   # do not flag shares computed on fewer tagged records than this (small-sample noise)
CORR = re.compile(r'CORRECTION|Retracted|upgrades an earlier inference|Correction of an earlier|corrects an earlier', re.I)


def pct(a, b):
    return '%d%%' % round(100 * a / b) if b else '-'


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--out', default=os.path.join('indexes', 'review.md')); ap.add_argument('--clone1'); ap.add_argument('--clone2')
    ap.add_argument('--maintainers', default='', help='comma list of maintainer logins (default: project.json)')
    ap.add_argument('--sparse-ok', default='constraint,target,proto,z2', help='facets that are sparse by design (not flagged)')
    a = ap.parse_args()
    R = []
    for k, p in pz.all_records():
        fm, s, nt = pz.parse(p); R.append((k, pz.repo_of(p), fm, s))
    L = ['# Dataset health review (generated by `review.py`; do not edit)', '']; att = []
    # 1 coverage
    L += ['## Coverage and depth', '', '| corpus | kind | records | analysed | by depth |', '|---|---|---|---|---|']
    for repo in pz.REPOS:
        for k in ('issue', 'commit'):
            rs = [x for x in R if x[0] == k and x[1] == repo]
            if not rs: continue
            d = collections.Counter(x[2]['depth'] for x in rs)
            L.append('| %s | %s | %d | %s | %s |' % (repo, k, len(rs), pct(sum(1 for x in rs if x[2]['status'] == 'analyzed'), len(rs)), ', '.join('%s %d' % (kk, v) for kk, v in sorted(d.items()))))
            if k == 'commit' and d.get('title', 0) / len(rs) > 0.9: att.append('%s commits: %s are at title depth (subject and files only)' % (repo, pct(d['title'], len(rs))))
    # 2 facet population
    L += ['', '## Facet population (manually tagged records)', '']
    for k in ('issue', 'commit'):
        rs = [x for x in R if x[0] == k and x[2]['tagged_by'] == 'manual']
        if not rs: continue
        fc = collections.Counter(f for x in rs for f in {t.split(':')[0] for t in x[2]['tags']})
        L.append('- **%s** (%d records): ' % (k, len(rs)) + ', '.join('%s %s' % (f, pct(v, len(rs))) for f, v in fc.most_common()))
        for f, v in (fc.items() if len(rs) >= MIN_N else []):
            if v / len(rs) < 0.15 and f not in set(a.sparse_ok.split(',')): att.append('%s facet `%s` is on only %s of %s records' % (k, f, pct(v, len(rs)), k))
    # 3 classes
    L += ['', '## Problem classes', '']
    cc = collections.Counter(); lay = collections.defaultdict(collections.Counter)
    for k, repo, fm, s in R:
        st = 'human' if fm['classes'] else ('inferred' if fm.get('classes_inferred') else 'none'); cc[(repo, k, st)] += 1
        L1 = [t.split(':')[1] for t in fm['tags'] if t.startswith('layer:')]
        if fm['classes'] and L1 and k == 'issue': lay[L1[0]][fm['classes'][0][0]] += 1
    L.append('| corpus | kind | human | inferred | none |'); L.append('|---|---|---|---|---|')
    for repo in pz.REPOS:
        for k in ('issue', 'commit'):
            t = sum(v for (r, kk, s_), v in cc.items() if r == repo and kk == k)
            if t: L.append('| %s | %s | %d | %d | %d |' % (repo, k, cc[(repo, k, 'human')], cc[(repo, k, 'inferred')], cc[(repo, k, 'none')]))
    tot = sum(sum(c.values()) for c in lay.values())
    if tot:
        pur = sum(c.most_common(1)[0][1] for c in lay.values()) / tot
        L += ['', 'Class letter predicted by the primary `layer` tag alone: **%d%%** (%d classed issues).' % (round(100 * pur), tot)]
        if pur > 0.8 and tot >= MIN_N: att.append('class letters are %d%% predictable from `layer` (the top level of the class scheme duplicates a facet)' % round(100 * pur))
    # thin classes
    per = collections.Counter(c for k, repo, fm, s in R for c in fm['classes'])
    cls = json.load(open(pz.CLS, encoding='utf-8')) if os.path.exists(pz.CLS) else {}
    thin = sorted(c for c in cls if per[c] < 3)
    if thin: L.append('Classes with fewer than three hand-cited records: %s.' % ', '.join(thin)); att.append('%d classes have fewer than three hand-cited records (%s)' % (len(thin), ', '.join(thin[:8])))
    # 4 citations
    L += ['', '## Citation coverage (records cited by an analysis document or registry page)', '']
    for k in ('issue', 'commit'):
        deep = [x for x in R if x[0] == k and x[2]['depth'] in ('full', 'source')]
        cited = [x for x in R if x[0] == k and x[2]['cited_in']]
        L.append('- %s: %d cited of %d records (%s); read in full/source but uncited: %d' % (k, len(cited), sum(1 for x in R if x[0] == k), pct(len(cited), sum(1 for x in R if x[0] == k)), sum(1 for x in deep if not x[2]['cited_in'])))
    ci = sum(1 for x in R if x[0] == 'issue' and x[2]['cited_in']); ti = sum(1 for x in R if x[0] == 'issue')
    if ti and ci / ti < 0.4: att.append('only %s of issues are cited by any document: the narrative carries a fraction of what the records hold' % pct(ci, ti))
    # 5 time concentration
    L += ['', '## Time concentration (issues per half-year, primary corpus)', '']
    hy = collections.Counter(); z1 = [x for x in R if x[0] == 'issue' and x[1] == 'z1']
    for k, repo, fm, s in z1: hy[fm['date'][:4] + ('H1' if int(fm['date'][5:7]) <= 6 else 'H2')] += 1
    if hy:
        top = hy.most_common(3); L.append(', '.join('%s %d (%s)' % (h, n, pct(n, len(z1))) for h, n in top))
        if top[0][1] / len(z1) > 0.3: att.append('%s holds %s of the primary corpus issues: statistics about "typical" behaviour are dominated by one period' % (top[0][0], pct(top[0][1], len(z1))))
    # 6 confidence and outcomes
    L += ['', '## Confidence and outcomes (issues)', '']
    iss = [x for x in R if x[0] == 'issue' and x[2]['tagged_by'] == 'manual']
    conf = collections.Counter(t for x in iss for t in x[2]['tags'] if t.startswith('conf:')); out = collections.Counter(t for x in iss for t in x[2]['tags'] if t.startswith('outcome:'))
    if conf: L.append('- conf: ' + ', '.join('%s %s' % (t[5:], pct(v, sum(conf.values()))) for t, v in conf.most_common()))
    if out: L.append('- outcome: ' + ', '.join('%s %s' % (t[8:], pct(v, sum(out.values()))) for t, v in out.most_common(6)))
    st = conf.get('conf:stated', 0)
    if sum(conf.values()) >= MIN_N and st / sum(conf.values()) > 0.7: att.append('%s of tagged issues rest on a maintainer statement (`conf:stated`): single-source knowledge, not tested' % pct(st, sum(conf.values())))
    unk = out.get('outcome:unknown', 0)
    if sum(out.values()) >= MIN_N and unk / sum(out.values()) > 0.2: att.append('%s of issues have no visible resolution (`outcome:unknown`)' % pct(unk, sum(out.values())))
    # 7 corrections, constraints, duplicate summaries
    corr = [x for x in R if CORR.search(x[3])]
    L += ['', '## Corrections and constraints', '', '- records whose summary records a correction, retraction or upgrade: **%d**' % len(corr)]
    cons = [x for x in R if any(t.startswith('constraint:') for t in x[2]['tags'])]
    if cons:
        unc = sum(1 for x in cons if not x[2]['cited_in']); L.append('- constraint-tagged records: %d; not cited by any document or registry page: %d (%s)' % (len(cons), unc, pct(unc, len(cons))))
        if unc / len(cons) > 0.5: att.append('%s of constraint-tagged records are uncited: write or refresh the rule catalogue (P14)' % pct(unc, len(cons)))
    heads = collections.Counter(re.sub(r'\W+', ' ', x[3][:120].lower()).strip() for x in R if x[3])
    dup = sum(v for v in heads.values() if v > 1)
    if sum(heads.values()) and dup / sum(heads.values()) > 0.5: att.append('%s of records share their summary opening with another record: summaries are often group-level, so per-record text is weak evidence' % pct(dup, sum(heads.values())))
    L.append('- records sharing an identical 120-character summary opening with another record: %d of %d (group-tagged lines produce this)' % (dup, sum(heads.values())))
    # 8 maintainer behaviour
    m = set(x for x in a.maintainers.split(',') if x) or (set(json.load(open(os.path.join(pz.ROOT, 'project.json'))).get('maintainers', [])) if os.path.exists(os.path.join(pz.ROOT, 'project.json')) else set())
    for cache, name in (('.cache/full', 'primary'), ('.cache/full-z2', 'secondary')):
        d = os.path.join(pz.ROOT, cache)
        if not (os.path.isdir(d) and m): continue
        th = [json.load(open(os.path.join(d, f), encoding='utf-8')) for f in os.listdir(d)]
        lat, zero, by = [], 0, collections.defaultdict(lambda: [0, 0])
        for o in th:
            if o['author'] in m: continue
            mm = [c for c in o['comments'] if c['a'] in m]; y = o['created'][:4]; by[y][0] += 1
            if not mm: zero += 1; by[y][1] += 1; continue
            lat.append((datetime.date.fromisoformat(mm[0]['d']) - datetime.date.fromisoformat(o['created'])).days)
        if lat:
            if name == 'primary': L += ['', '## Maintainer behaviour (from the thread caches)', '']
            L.append('- %s corpus: %d threads by others; **no maintainer reply: %s**; first reply median %s day(s), p90 %s; same-day %s' % (name, len(th), pct(zero, sum(v[0] for v in by.values())), statistics.median(lat), sorted(lat)[int(len(lat) * 0.9)], pct(sum(1 for x in lat if x == 0), len(lat))))
            L.append('  - no-reply share by year: ' + ', '.join('%s %s' % (y, pct(v[1], v[0])) for y, v in sorted(by.items()) if v[0] >= 10))
            if zero / max(1, sum(v[0] for v in by.values())) > 0.2: att.append('%s of %s threads never got a maintainer reply' % (pct(zero, sum(v[0] for v in by.values())), name))
    for clone, name in ((a.clone1, 'primary'), (a.clone2, 'secondary')):
        if clone and os.path.isdir(clone):
            sl = subprocess.run(['git', '-C', clone, 'shortlog', '-sn', '--all'], capture_output=True, text=True).stdout.strip().split('\n')
            n = [int(x.split('\t')[0]) for x in sl if x.strip()]
            if n:
                L.append('- %s repository: top committer %s of %d commits' % (name, pct(n[0], sum(n)), sum(n)))
                if n[0] / sum(n) > 0.8: att.append('%s repository: one person wrote %s of the commits (bus factor 1; the corpus reflects one expert)' % (name, pct(n[0], sum(n))))
    L = L[:2] + ['## ATTENTION (things to know before relying on the dataset)', ''] + (['- ' + x for x in att] or ['- none triggered']) + [''] + L[2:]
    os.makedirs(os.path.dirname(os.path.join(pz.ROOT, a.out)), exist_ok=True)
    open(os.path.join(pz.ROOT, a.out), 'w', encoding='utf-8').write('\n'.join(L) + '\n')
    print('review written to %s (%d attention items)' % (a.out, len(att)))
    for x in att: print('  ATTENTION:', x)


if __name__ == '__main__':
    main()
